" Information {{{
"
" My personal vimrc file.
"
" Maintainer: Drew Silcock <drew@drewsilcock.co.uk>
" Last modified: 23rd October 2019
"
" }}}

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

set nocompatible
call plug#begin('~/.vim/plugged')

"
" Must Haves
"

" Sensible defaults from Tim Pope
Plug 'tpope/vim-sensible'
" Better finding
Plug 'easymotion/vim-easymotion'
" ctrl-p file
Plug 'ctrlpvim/ctrlp.vim'
" Automatic tab settings
Plug 'tpope/vim-sleuth'
" Sublime-esque multi cursors
Plug 'terryma/vim-multiple-cursors'
" Autocomplete for code
Plug 'ycm-core/YouCompleteMe'
" Airline (like Powerline but lighter weight)
Plug 'vim-airline/vim-airline'
" With themes
Plug 'vim-airline/vim-airline-themes'

"
" Languages
"

" Mega language pack
Plug 'sheerun/vim-polyglot'
" Hex editor
Plug 'fidian/hexmode'
" CSV column highlighting
Plug 'chrisbra/csv.vim'
" Linting
Plug 'w0rp/ale'
" Rust functionality
Plug 'rust-lang/rust.vim'
" RON (Rust Object Notation) plugin
Plug 'ron-rs/ron.vim'

"
" Misc
"

" show VCS diff in gutter
Plug 'mhinz/vim-signify'
" quickly change surroundings - (), '', etc
Plug 'tpope/vim-surround'
" quickly comment out stuff
Plug 'tpope/vim-commentary'
" show indent level
Plug 'yggdroot/indentline'
let g:indentLine_char = '▏'
" Highlight whitespace
Plug 'ntpeters/vim-better-whitespace'
" quickly align things
Plug 'godlygeek/tabular'

" Markdown
Plug 'plasticboy/vim-markdown'
" Markdown plugin is great but folding is awful.
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_conceal = 0

" autocomplete quotes, parenthesis, brackets, etc.
Plug 'cohama/lexima.vim'
"let g:lexima_enable_newline_rules = 1

" close files and keep layouts
Plug 'moll/vim-bbye'
" Buffers as tabs
Plug 'ap/vim-buftabline'
" Git wrapper
Plug 'tpope/vim-fugitive'
" Git browser
Plug 'junegunn/gv.vim'

" Colour theme
Plug 'lifepillar/vim-solarized8'

" writng mode
Plug 'junegunn/goyo.vim'

call plug#end()

"set backupdir=~/.vim/tmp
"set directory=~/.vim/tmp

hi Pmenu ctermbg=0 ctermfg=8
hi PmenuSel ctermfg=2

filetype plugin indent on
set backspace=indent,eol,start

" full colours
if has("termguicolors")
  set termguicolors
endif
syntax on
set background=dark
let g:one_allow_italics = 1 " I love italic for comments
colorscheme solarized8

" encoding
set encoding=utf-8
scriptencoding utf-8

" local vimrc
set exrc
set secure

" tab sizes
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" line numbers
set number

" move through wrapped lines
vmap j gj
vmap k gk
nmap j gj
nmap k gk

" easymotion
map / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)
map <Leader>l <Plug>(easymotion-lineforward)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
map <Leader>h <Plug>(easymotion-linebackward)
map n <Plug>(easymotion-next)
map N <Plug>(easymotion-prev)
let g:EasyMotion_smartcase = 1

" Ctrl-P
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']

" new file in vertical split
nnoremap <c-N> :vnew<CR>

" multi cursor
let g:multi_cursor_use_default_mapping=0
" Default mapping
let g:multi_cursor_next_key='<C-d>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'
" Map start key separately from next key
let g:multi_cursor_start_key='<c-d>'

" next and prev buffer
set hidden
nnoremap <tab> :bnext<CR>
nnoremap <S-tab> :bprev<CR>

let g:vim_markdown_conceal = 0

" F2 to build
map <F2> :w \| make<CR>

" True colour support in tmux; see: https://tomlankhorst.nl/iterm-tmux-vim-true-color/
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" Tab navigation like Firefox or Chrome
nnoremap <C-tab>   :tabnext<CR>
nnoremap <C-S-tab> :tabprevious<CR>
nnoremap <S-left>  :tabprevious<CR>
nnoremap <S-right> :tabnext<CR>
nnoremap <C-t>     :tabnew .<CR>
nnoremap <C-w>     :tabclose<CR>

inoremap <C-tab>   <Esc>:tabprevious<CR>a
inoremap <C-S-tab> <Esc>:tabnext<CR>a
inoremap <S-left>  <Esc>:tabprevious<CR>a
inoremap <S-right> <Esc>:tabnext<CR>a
inoremap <C-t>     <Esc>:tabnew .<CR>
inoremap <C-w>     <Esc>:tabclose<CR>a

let g:ycm_autoclose_preview_window_after_insertion = 1
let g:ycm_autoclose_preview_window_after_completion = 1

" Enable mouse for all things
set mouse=a

" Fix Shift-Left / Shift-Right keys in vim in tmux
set term=xterm-256color

nnoremap <C-g> :YcmCompleter GoTo<CR>
inoremap <C-g> :YcmCompleter GoTo<CR>

" Preview pad goes on the bottom, not the top.
set splitbelow

" Airline
let g:airline_symbols = {}
let g:airline_theme='solarized'
let g:airline_powerline_fonts=1
" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'
" Airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

" If I wanted things concealing, I wouldn't be using vim.
set conceallevel=0
